// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdbnphzslqfofbiguhth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkYm5waHpzbHFmb2ZiaWd1aHRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzI1NTgsImV4cCI6MjA2Njk0ODU1OH0.tRxiC3yEZQaAUlmqGq0Yv48ZQFRSJo5u8PqRxov8ZWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});